name: Deploy to Firebase Hosting on PR

on:
pull_request:
  branches:
    - master

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set environment variables for the build process
      - name: Set up environment variables
        run: |
          echo "VITE_APP_PORT=${{ secrets.VITE_APP_PORT }}" >> .env
          echo "VITE_APP_CLIENT_ID=${{ secrets.VITE_APP_CLIENT_ID }}" >> .env
          echo "VITE_APP_AUTH_API_BASE_ENDPOINT=${{ secrets.VITE_APP_AUTH_API_BASE_ENDPOINT }}" >> .env
          echo "VITE_APP_API_ENDPOINT=${{ secrets.VITE_APP_API_ENDPOINT }}" >> .env
          echo "VITE_APP_REDIRECT_ENDPOINT=${{ secrets.VITE_APP_REDIRECT_ENDPOINT }}" >> .env

      - name: Print .env file
        run: cat .env

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MYMUSIC_1144 }}
          channelId: mymusic-1144
          projectId: mymusic-1144
