name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - master # The branch to trigger the deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up environment variables
      - name: Set up environment variables
        run: |
          echo "VITE_APP_PORT=${{ secrets.VITE_APP_PORT }}" >> .env
          echo "VITE_APP_CLIENT_ID=${{ secrets.VITE_APP_CLIENT_ID }}" >> .env
          echo "VITE_APP_AUTH_API_BASE_ENDPOINT=${{ secrets.VITE_APP_AUTH_API_BASE_ENDPOINT }}" >> .env
          echo "VITE_APP_API_ENDPOINT=${{ secrets.VITE_APP_API_ENDPOINT }}" >> .env
          echo "VITE_APP_REDIRECT_ENDPOINT=${{ secrets.VITE_APP_REDIRECT_ENDPOINT }}" >> .env

      - name: Print .env file
        run: cat .env

      - name: Install dependencies
        run: npm ci # Use npm ci for clean install based on package-lock.json

      - name: Build project
        run: npm run build # Build the React app with Vite

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MYMUSIC_1144 }}
          projectId: mymusic-1144 # Your Firebase project ID
